### ISSUE TITLE
OAUTH seems to be broken to NetProfiler

### ISSUE THREAD

**Issue by cmc-rvbd** [riverbed/steelscript-netprofiler#9]
I have an existing script that uses OAUTH to when creating Host Groups on a NetProfiler. After upgrading to the Riverbed-Community repo version of SteelScript, this script no longer works. I verified that the issue seems to be in the latest version of SteelScript by running the "top_ports.py" example script with the OAUTH authentication and with username/password authentication - only the OAUTH test failed. Meanwhile, the same script run with the same arguments using the "old" version of SteelScript ("docker run -it riverbed/steelscript") works.

```
# python top_ports.py --oauth="ewoJIm5vbmNlIjogIjY0ZjI1NWQyIiwKCSJhdWQiOiAiaHR0cDovL24zMS1wcmYvYXBpL2NvbW1vbi8xLjAvb2F1dGgvdG9rZW4iLAoJImlzcyI6ICJodHRwOi8vbjMxLXByZiIsCgkicHJuIjogImFkbWluIiwKCSJqdGkiOiAiMSIsCgkiZXhwIjogIjE3NjEwNTQzMjEiLAoJImlhdCI6ICIxNzI5NTE4MzIxIgp9" n31-prf
Traceback (most recent call last):
  File "/root/steelscript-workspace/examples/steelscript-netprofiler/top_ports.py", line 41, in <module>
    TopPortsApp().run()
  File "/src/steelscript/steelscript/common/app.py", line 35, in run
    self.parse(sys.argv[1:])
  File "/src/steelscript/steelscript/commands/steel.py", line 307, in parse
    self.setup()
  File "/src/steelscript-netprofiler/steelscript/netprofiler/core/app.py", line 28, in setup
    self.netprofiler = NetProfiler(self.options.host,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/steelscript-netprofiler/steelscript/netprofiler/core/netprofiler.py", line 66, in __init__
    super(NetProfiler, self).__init__("profiler", host, port,
  File "/src/steelscript/steelscript/common/service.py", line 228, in __init__
    self.authenticate(auth)        
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/steelscript/steelscript/common/service.py", line 412, in authenticate
    raise RvbdException("No supported authentication methods")
steelscript.common.exceptions.RvbdException: No supported authentication methods
```

**Comment by cmc-rvbd** [comment]
Here is the same command working with username/password authentication:
```
python top_ports.py -u admin -p password n31-prf[ ['tcp/3389', 'ms-wbt-server', 22010.3474359, 0.00021],
  ['tcp/443', 'https', 7719.60384615, 0.01105],
  ['tcp/80', 'http', 2334.83205128, 0.01054],
  ['tcp/22', 'ssh', 1367.18974359, 0.0257],
  ['tcp/143', 'imap', 704.647435897, ''],
  ['tcp/41017', 'mnmp', 325.556410256, 0.00012],
  ['udp/53', 'domain', 129.312820513, ''],
  ['tcp/23', 'telnet', 21.2948717949, 0.00529],
  ['tcp/1129', 'saphostctrls', 18.9743589744, 0.01293],
  ['ospf', 'ospf', 6.82051282051, ''],
  ['tcp/445', 'microsoft-ds', 6.76923076923, ''],
  ['tcp/135', 'epmap', 6.0, 0.00061],
  ['udp/123', 'ntp', 2.53333333333, '']]
```
And here is the same command working just fine with the old SteelScript version:
```
# python top_ports.py --oauth="ewoJIm5vbmNlIjogIjY0ZjI1NWQyIiwKCSJhdWQiOiAiaHR0cDovL24zMS1wcmYvYXBpL2NvbW1vbi8xLjAvb2F1dGgvdG9rZW4iLAoJImlzcyI6ICJodHRwOi8vbjMxLXByZiIsCgkicHJuIjogImFkbWluIiwKCSJqdGkiOiAiMSIsCgkiZXhwIjogIjE3NjEwNTQzMjEiLAoJImlhdCI6ICIxNzI5NTE4MzIxIgp9" n31-prf
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/src/steelscript-netprofiler/steelscript/netprofiler/core/report.py:381: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  start = time.clock()
[ ['tcp/3389', 'ms-wbt-server', 26488.6397436, 0.0002],
  ['tcp/443', 'https', 8342.37564103, 0.01393],
  ['tcp/80', 'http', 7285.4474359, 0.00721],
  ['tcp/22', 'ssh', 1367.18974359, 0.0257],
  ['tcp/143', 'imap', 704.647435897, ''],
  ['tcp/41017', 'mnmp', 402.492307692, 0.00013],
  ['udp/53', 'domain', 162.306410256, ''],
  ['tcp/23', 'telnet', 38.1051282051, 0.00529],
  ['tcp/1129', 'saphostctrls', 18.9743589744, 0.01293],
  ['ospf', 'ospf', 8.18461538462, ''],
  ['tcp/445', 'microsoft-ds', 8.06666666667, ''],
  ['tcp/135', 'epmap', 6.0, 0.00061],
  ['udp/123', 'ntp', 3.31282051282, '']]
```
